# Form implementation generated from reading ui file 'Forms/Auth.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Auth_dialog(object):
    def setupUi(self, Auth_dialog):
        Auth_dialog.setObjectName("Auth_dialog")
        Auth_dialog.resize(312, 146)
        self.gridLayout = QtWidgets.QGridLayout(Auth_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Last_name_text = QtWidgets.QLineEdit(parent=Auth_dialog)
        self.Last_name_text.setObjectName("Last_name_text")
        self.gridLayout.addWidget(self.Last_name_text, 0, 1, 1, 1)
        self.last_name_lable = QtWidgets.QLabel(parent=Auth_dialog)
        self.last_name_lable.setObjectName("last_name_lable")
        self.gridLayout.addWidget(self.last_name_lable, 0, 0, 1, 1)
        self.password_lable = QtWidgets.QLabel(parent=Auth_dialog)
        self.password_lable.setObjectName("password_lable")
        self.gridLayout.addWidget(self.password_lable, 1, 0, 1, 1)
        self.Password_text = QtWidgets.QLineEdit(parent=Auth_dialog)
        self.Password_text.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_text.setObjectName("Password_text")
        self.gridLayout.addWidget(self.Password_text, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Status_label = QtWidgets.QLabel(parent=Auth_dialog)
        self.Status_label.setStyleSheet("color: red")
        self.Status_label.setText("")
        self.Status_label.setObjectName("Status_label")
        self.horizontalLayout.addWidget(self.Status_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Auth_button = QtWidgets.QPushButton(parent=Auth_dialog)
        self.Auth_button.setEnabled(False)
        self.Auth_button.setMinimumSize(QtCore.QSize(100, 0))
        self.Auth_button.setObjectName("Auth_button")
        self.horizontalLayout.addWidget(self.Auth_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)

        self.retranslateUi(Auth_dialog)
        QtCore.QMetaObject.connectSlotsByName(Auth_dialog)

    def retranslateUi(self, Auth_dialog):
        _translate = QtCore.QCoreApplication.translate
        Auth_dialog.setWindowTitle(_translate("Auth_dialog", "Вход"))
        self.last_name_lable.setText(_translate("Auth_dialog", "Фамилия"))
        self.password_lable.setText(_translate("Auth_dialog", "Пароль"))
        self.Auth_button.setText(_translate("Auth_dialog", "Вход"))
